# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/e1e864d9-29fb-42a7-9c21-6a51ee598c74";
      fsType = "ext4";
    };

  boot.initrd.luks.devices = {
    luksRoot = {
      device = "/dev/disk/by-uuid/d9952097-101a-4127-8874-74bcab4b6b9d";
      keyFile = "/dev/sda";
      keyFileSize = 4096;
      allowDiscards = true;
    };
    luksSwap = {
      device = "/dev/disk/by-uuid/163ee892-f157-4234-94d8-8776049814fa";
      keyFile = "/dev/sda";
      keyFileSize = 4096;
      allowDiscards = true;
    };
  };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/17D9-EECC";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [{
      device = "/dev/mapper/luksSwap";
    }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp61s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
